### ISSUE TITLE
YST 7.2.5 加密环境下么无效

### ISSUE THREAD

**Issue by liuyuqingenglish** [liliwen365/Python#1]
7.2.5版本验证无效  哥们你测试的加密环境版本是多少啊

**Comment by liliwen365** [comment]
内核版本6.8.2，解密原理是：利用浏览器上传到内存中的数据，此时数据是解密状态（这个是一个漏洞），在新建一个同名的文件，利用python的隐式写入文件。理论上你的如果你从浏览器上传到内存中的数据是解密状态的，就可以用解密状态的内存数据新建一个同名的新文件。你可以用print函数在服务器后台打印一下同一份文件的在加密带锁和不带锁上传后，在服务器后台打印出来的二进制文件是不是一致的。如果不一致，说明上传到浏览器的文件本身没有解密，这个漏洞已经被你现在的版本策略更新了！
