### ISSUE TITLE
xlsm带宏的文件和文件大小超过20MB的无法解密

### ISSUE THREAD

**Issue by wuliang365702** [liliwen365/Python#7]
经测试大部分情况下能够解密，但是xlsm格式和文件较大的excel解密无效

**Comment by liliwen365** [comment]
xlsm文件，手动更改后缀为xlsx后，在上传；再手动改回xlsm后缀即可；

**Comment by wuliang365702** [comment]
> xlsm文件，手动更改后缀为xlsx后，在上传；再手动改回xlsm后缀即可；

It's a good way，thank you！
